s3:
  input_bucket: "yellow-taxi-files-anice"
  output_bucket: "yellow-taxi-files-anice"
  #aws_access_key: "colocar aqui o access key"
  #aws_secret_key: "colocar aqui o secret key"

pipeline:
  months:
    - "2023-01"
    - "2023-02"
    - "2023-03"
    - "2023-04"
    - "2023-05"
  
  maonths:
    - "January"
    - "February"
    - "March"
    - "April"
    - "May"

  fields:
    - "VendorID"
    - "passenger_count"
    - "total_amount"
    - "tpep_pickup_datetime"
    - "tpep_dropoff_datetime"

  file_url : "https://d37ci6vzurychx.cloudfront.net/trip-data/"
